version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      PORT: 8080
      REDIS_URL: redis:6379
    networks:
      - backend
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
